name: 寻寻觅觅
description: Coding + Muisc + Life
meta_description: "enjoy life + coding + music"

baseurl: /
markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://dingk-r.github.io/rss'
author:         'DKR'
