name: 寻寻觅觅
description: 码农＋程序＋记录＋吐槽＋音乐＋生活
meta_description: "enjoy life + coding + music"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'DKR'
